version: "3.8"

services:
  chatbot-api:
    build: .
    container_name: chatbot-api
    ports:
      - "8000:8000" # FastAPI port
      - "11434:11434" # Ollama port
    env_file:
      - .env
    volumes:
      - ollama_data:/root/.ollama # Persist Ollama models and data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  ollama_data:
    driver: local
